local model = {};
model.vid = load_3dmodel("models/apb/01_apb_marquee.ctm");
add_3dmesh(model.vid, "models/apb/02_apb_screen.ctm");
add_3dmesh(model.vid, "models/apb/apb_backside.ctm");
add_3dmesh(model.vid, "models/apb/apb_belowmarquee.ctm");
add_3dmesh(model.vid, "models/apb/apb_back.ctm");
add_3dmesh(model.vid, "models/apb/apb_backside.ctm");
add_3dmesh(model.vid, "models/apb/apb_belowmarquee.ctm");
add_3dmesh(model.vid, "models/apb/apb_bezel.ctm");
add_3dmesh(model.vid, "models/apb/apb_button01.ctm");
add_3dmesh(model.vid, "models/apb/apb_button02.ctm");
add_3dmesh(model.vid, "models/apb/apb_button03.ctm");
add_3dmesh(model.vid, "models/apb/apb_button04.ctm");
add_3dmesh(model.vid, "models/apb/apb_coinpanel.ctm");
add_3dmesh(model.vid, "models/apb/apb_cpo.ctm");
add_3dmesh(model.vid, "models/apb/apb_inside.ctm");
add_3dmesh(model.vid, "models/apb/apb_leftpanel.ctm");
add_3dmesh(model.vid, "models/apb/apb_rightpanel.ctm");
add_3dmesh(model.vid, "models/apb/apb_seat.ctm");
add_3dmesh(model.vid, "models/apb/apb_seatpole1.ctm");
add_3dmesh(model.vid, "models/apb/apb_seatpole2.ctm");
add_3dmesh(model.vid, "models/apb/apb_seatpole3.ctm");
add_3dmesh(model.vid, "models/apb/apb_speaker.ctm");
add_3dmesh(model.vid, "models/apb/apb_top.ctm");
add_3dmesh(model.vid, "models/apb/apb_wheelbase.ctm");
add_3dmesh(model.vid, "models/apb/apb_wheelcircle.ctm");
add_3dmesh(model.vid, "models/apb/apb_wheelmiddle.ctm");
add_3dmesh(model.vid, "models/apb/apb_wheelshaft.ctm");
image_framesetsize(model.vid, 25);
scale_3dvertices(model.vid);
return model;
