-- bond_target
-- @short: Setup a state transfer pipe between two targets.
-- @inargs: vid:source, vid:dest
-- @inargs: vid:source, vid:dest, bool:blob
-- @inargs: vid:source, vid:dest, bool:blob, string:identifier
-- @outargs:
-- @longdescr: This function is used to setup a state transfer
-- stream between two targets. A pipe-pair is created with the
-- write- end sent to *source* and the read- end sent to *dest*.
-- By default, the transfer target type is marked as 'state',
-- meaning that *dest* should replace its runtime state with
-- that of *source. If the *blob* argument is set to true, then
-- the transfer type will be that of a opaque data blob, up
-- to the *dest* to figure out what to do with.
-- @group: targetcontrol
-- @cfunction: targetbond
-- @related:
