-- build_pointcloud
-- @short: Create a 3D object that is comprised of a cloud of points.
-- @inargs: pointcount, *nmaps*
-- @outargs: vid
-- @longdescr: Evenly distribute *pointcount* points in a bounding
-- volume from -1,-1,-1 to 1,1,1. This is primarily intended to be
-- manipulated with a vertex shader and a possible lookup texture.
-- @group: 3d
-- @cfunction: pointcloud
-- @related:
-- @flags:

