-- net_push
-- @short: Transfer *srcobj* through the connection defined by *netvid*.
-- @inargs: netvid, srcobj
-- @outargs:
-- @longdescr:
-- @group: network
-- @cfunction: net_pushcl
-- @flags: experimental
