-- net_push_srv
-- @short: Transfer *srcobj* to a single connection or a group of connected users.
-- @inargs: srvvid, srcobj, *domain*
-- @outargs:
-- @longdescr:
-- @note: By default, domain is 0 (broadcast). Other possible domains are specific connection ID
-- and specifal groups based on connection state (net_authenticate).
-- @group: network
-- @cfunction: net_pushsrv
-- @flags: experimental

