-- net_listen
-- @short: Spawn a server session, listening for incoming connections.
-- @inargs: callback
-- @outargs: vid
-- @longdescr: Launch a new frameserver in networking server mode. The *callback*
-- argument will be used as an event trigger for conveying all client related events.
-- For the contents of such triggers, see the notes.
-- @group: network
-- @cfunction: arcan_lua_net_listen
-- @flags: experimental

