-- net_open
-- @short: Open an external connection to an external host
-- @inargs: hostid, callback
-- @outargs: vid
-- @longdescr:
-- @group: network
-- @cfunction: arcan_lua_net_open
-- @flags: experimental
