-- resume_movie
-- @short: Resume playback of a previously paused decode frameserver.
-- @inargs: movievid
-- @longdescr: There are two principal pause/resume mechanisms that
-- overlap slightly. resume_movie guarantee that the audio/video playback
-- sampling will be paused in the main engine. This implies that queued
-- buffers (decode- sessions can maintain a preset number of cached audio/video
-- frames) will be kept intact. The related resume_target sends a request
-- to the target frameserver or hijack sessions and blocks the process to
-- whatever extent is possible.
-- @group: targetcontrol
-- @cfunction: resumemovie
-- @related: resume_target

