-- stepframe_target
-- @short: Request that the target generate / consume a video frame.
-- @inargs: targetid, *n_frames*
-- @longdescr: Some external targets either require, or can be set to
-- require, a frame-pulse that hints when it should emit, consume
-- or ignore one or several video frames, especially for non-realtime tasks.
-- This is handled as events passed on the event-queue, in order to wake
-- processes that idle or sleep when no event has been received.
-- @note: n_frames (default:1) should be set to 0 > n > INT_MAX.
-- @note: stepframe can also be used on record and calctargets and will
-- then force a readback.
-- @group: targetcontrol
-- @related: define_calctarget, define_recordtarget
-- @cfunction: arcan_lua_targetstepframe

