-- suspend_target
-- @short: Request that the target suspend execution,
-- awaiting a resume or terminate call.
-- @inargs: targetvid, *noblock_fsrv*
-- @longdescr:
-- Suspend target blocks data retrieval from the specific frameserver.
-- By default, it is performed in both the frameserver polling layer
-- on the arcan side, and as an event received by the frameserver.
-- If *noblock_fsrv* is set to something ther than 0, only the hinting
-- event is sent.
-- @group: targetcontrol
-- @cfunction: targetsuspend
-- @related: resume_target

