-- target_postfilter_args
-- @short: Modify the postfilter state parameters for the targetted frameserver.
-- @inargs: vid, group, *v1*, *v2*, *v3*
-- @note: The nots for target_postfilter applies here also. 
-- @group: targetcontrol 
-- @cfunction: arcan_lua_targetpostfilterargs
-- @related: target_postfilter 
--
