-- text_dimensions
-- @short: Calculate the output volume of a format string.
-- @inargs: message, *vspacing*, *tspacing*
-- @outargs: width, height
-- @longdescr: Text dimensions follow many of the same rules and restrictions
-- as render_text, with the notable exception that it does not produce
-- any output.
-- @note: Global text- rendering state can still be affected, e.g. the
-- currently loaded font and style.
-- @group: image
-- @cfunction: strsize
-- @exampleappl: tests/interactive/fonttest
-- @related: render_text

