	string(ASCII 27 Esc)
	set(CL_RST "${Esc}[m")
	set(CL_RED "${Esc}[31m")
	set(CL_GRN "${Esc}[32m")
	set(CL_YEL "${Esc}[33m")
	set(CL_BLU "${Esc}[34m")
	set(CL_MAG "${Esc}[35m")
	set(CL_CYN "${Esc}[36m")
	set(CL_WHT "${Esc}[37m")
	set(CLB_RED "${Esc}[1;31m")
	set(CLB_GRN "${Esc}[1;32m")
	set(CLB_YEL "${Esc}[1;33m")
	set(CLB_BLU "${Esc}[1;34m")
	set(CLB_MAG "${Esc}[1;35m")
	set(CLB_CYN "${Esc}[1;36m")
	set(CLB_WHT "${Esc}[1;37m")
