FIND_PATH( ESPEAK_INCLUDE_DIR NAMES speak_lib.h PATH_SUFFIXES espeak espeak-ng)
FIND_LIBRARY(ESPEAK_LIBRARIES NAMES espeak espeak-ng)

IF( ESPEAK_LIBRARIES )
	SET( ESPEAK_FOUND TRUE )
ENDIF( ESPEAK_LIBRARIES )
