.\" groff -man -Tascii aloadimage.1
.TH arcan 1 "August 2020" aloadimage "User manual"
.SH NAME
aloadimage \- Trivial image viewer for Arcan servers
.SH SYNOPSIS
.B aloadimage [global_options] file1 file2 ...

.SH DESCRIPTION
\fIaloadimage\fR displays images over an arcan connection point. Each image
is parsed in a separate and sandboxed process. If multiple images are provided,
a certain number of items will be processed in advance.

.SH OPTIONS
.IP "\fB\-a, \-\-aspect\fR" When forced to scale in order to fit source
image into output window, maintain source image aspect radio and pad with
a background color.

.IP "\FB-S, \-\-server\-size\fR"
Scale source images to fit server- suggested content size. This changes the
primary type from MEDIA (server side scaling) to APPLICATION (client defined
scaling).

.IP "\fB\-l, \-\-loop\fR"
When the playlist reaches the end, it will loop back from the beginning
rather than shutting down.

.IP "\fB\-t, \-\-step\-time\fR"
Set the playlist automatic stepping time (default: 0, manual control). The time
unit is in ticks on a 25Hz clock.

.IP "\fB\-b, \-\-block-input\fR"
Ignore all keyboard and mouse input.

.IP "\fB\-d, \-\-display\fR \fIconnpath\fR"
By default, the ARCAN_CONNPATH environment is used in order to find an arcan
instance to connect to. This argument ignores that in favor for the connpath
argument.

.IP "\fB\-p, \-\-padcol\fR \fr,g,b,a\fR"
When running in a scalemode where source size != destination size and output
window cannot be resized, the default behavior is to center image and pad the
sides. This argument can override the default colors with the restriction that
all four channels should be provided and only decimal encoding in the range
0-255 is accepted.

.IP "\fB-m, \-\-limit\-mem\fR \fIlimit(mb)\fR"
Limit the maximum decoded memory sized allowed for eaching loading process.

.IP "\FB-r, \-\-readahead\fR \fIlimit(count)\fR"
Set the readahead limit for worker processes preloading playlist contents.

.IP "\fB-T, \-\-timeout\fR \fItimeout(seconds)\fR"
Stop/kill a worker process if it fails to decode an image within a certain
number of seconds.

.IP "\fX\-x, \-\-no\-sysflt\fR"
(build- option) aloadimage may be built with syscall filtering for worker
processes. This may break image loading in some environments/libc
implementations and may therefore need to be disabled.

.IP "\fX\-H, \-\-vr\fR"
attempt to connect as a VR compatible output, requires that the listening end
accepts HMD_L/R primary and secondary segment types. Playlist items should be
prefixed with the intended dominant eye, e.g. l:image_l.jpg r:image_r.jpg.

.IP "\fB\-h, \-\-help\fR"
Show a brief summary of commands and usage.

.SH ENVIRONMENT
.TP
.SM
\fBARCAN_CONNPATH\fR
Name of the connection point to use when connecting to arcan.
.TP
.SM
\fBARCAN_CONNKEY\fR
Key to use for authenticating againgst the connection path.

.SH COPYRIGHT
Copyright  ©  2017-2020 Bjorn Stahl. 3-clause BSD licensed. This is free software:
you are free  to  change and redistribute it. There is NO WARRANTY,
to the extent permitted by law.

.SH AUTHOR
Bjorn Stahl <contact at arcan-fe dot com>
